### ISSUE TITLE
2017-11-29-maintainance

### ISSUE THREAD

**Issue by zyzhang2-zz** [Blueve/LeetCodeUp#3]
Hello is this project still being maintained? I loaded it into my chromium but it doesn't seem to work.

**Comment by Blueve** [comment]
This project has not been maintained for a long time since I was working.
LeetCode released a lot of new features and also modify the page layout and making this plugin no longer work well.

Please feel free to fork this project and improve it on your side if needed.
And I'm willing to accept your pull request if you want to contribute this project.

BTW, I suppose that there are many similar projects or plugins (e.g. Greasemonkey-based script) you can use directly.

Hope that will helpful 😄
